### ISSUE TITLE
Gap between keyword and ability box if there is no Effect defined

### ISSUE THREAD

**Issue by Vallis13** [Lordbaconbane/aoswarscrollcreator#35]
Honestly, I'm not sure this needs a fix, as it only occurs in an ability with no Effect defined, which shouldn't be possible.  But...

If you create an ability, and leave the Effect field empty and add an ability Keyword, the Keyword box will not be attached to the ability box; there will be a gap between them.

**Comment by Lordbaconbane** [comment]
You will need to add a banner/text anyways so I'm going to pass on fixing this.
