### ISSUE TITLE
Ability boxes not fitting correctly

### ISSUE THREAD

**Issue by jowensm5702** [Lordbaconbane/aoswarscrollcreator#40]
![image](https://github.com/user-attachments/assets/d58ba39c-17a8-48b9-a2d2-2321a971359f)

There seems to be an issue with the boxes for abilities when you add slightly longer ability timings, or the bar across the top in general (I don't know how to describe it otherwise). I'm sorry if this was raised before and I missed it.

**Comment by Lordbaconbane** [comment]
Heya! I'll try and give this a repro. Thanks for raising it. If you can, can you export the warscroll and attach it here?

**Comment by Lordbaconbane** [comment]
I found the issue. The fix unfortunately means I need to change some things to my ability drawing so I'm going to spend a bit more time testing. Should be done soon, regardless

**Comment by Lordbaconbane** [comment]
![image](https://github.com/user-attachments/assets/3e31a742-0ca9-410e-a016-5db71eb090b3)

Pushing to production. Will be online shortly.
